// ============================================================================
// icon-name.js — 官方 iconName 解析（"style:name" 格式）
// ----------------------------------------------------------------------------
// 官方规范：iconName = "style:name"（Font Awesome 7.x：fas/far/fab）。
// v2 实现：图标库保留本地化 Bootstrap Icons（ICONS），值格式统一官方风格：
//   - "bs:check"   → Bootstrap 图标（本库扩展命名空间）
//   - "fas:house"  → 官方 FA 格式：查 FA→Bootstrap 映射表，命中渲染近似图标
// 未知图标返回 null（预览占位框、导出跳过）；非法格式（无 style 前缀）视为未知。
// ============================================================================

import { ICONS } from "./icon-library.js";

/** FA → Bootstrap 近似图标映射（常见图标；命名高度重合的 FA 键直接映射）。 */
const FA_TO_BS = {
  // 通用 / 界面
  "house": "house", "home": "house", "heart": "heart", "star": "star",
  "gear": "gear", "cog": "gear", "gears": "gear-wide-connected",
  "magnifying-glass": "search", "search": "search", "user": "person",
  "users": "people", "user-group": "people", "circle-user": "person-circle",
  "envelope": "envelope", "phone": "telephone", "camera": "camera",
  "image": "image", "images": "images", "file": "file-text",
  "folder": "folder", "folder-open": "folder2-open", "link": "link-45deg",
  "paperclip": "paperclip", "lock": "lock", "unlock": "unlock",
  "key": "key", "trash": "trash", "trash-can": "trash", "pen": "pencil",
  "pencil": "pencil", "eye": "eye", "eye-slash": "eye-slash",
  "bell": "bell", "bookmark": "bookmark-star", "calendar": "calendar",
  "clock": "clock", "stopwatch": "stopwatch", "flag": "flag",
  "tag": "tag", "tags": "tag", "trophy": "trophy", "medal": "award",
  "award": "award", "gem": "gem", "gift": "gift", "fire": "fire",
  "bolt": "lightning-charge", "zap": "lightning-charge", "sun": "sun",
  "moon": "moon", "cloud": "cloud", "droplet": "droplet", "snowflake": "snow",
  "leaf": "leaf", "globe": "globe-americas", "location-dot": "geo-alt",
  "map-pin": "pin-map", "map": "map", "compass": "compass", "route": "signpost",
  "building": "building", "bank": "bank", "landmark": "bank", "briefcase": "briefcase",
  "suitcase": "briefcase", "cart-shopping": "cart", "bag-shopping": "bag",
  "credit-card": "credit-card", "money-bill": "cash", "sack-dollar": "cash-stack",
  "percent": "percent", "calculator": "calculator", "chart-line": "graph-up",
  "chart-column": "bar-chart", "chart-pie": "pie-chart", "chart-bar": "bar-chart",
  "chart-area": "graph-up-arrow", "table": "table", "list": "list-ul",
  "list-ul": "list-ul", "list-ol": "list-ol", "check": "check",
  "check-double": "check2-all", "xmark": "x", "x": "x", "plus": "plus",
  "minus": "dash", "asterisk": "asterisk", "circle": "circle",
  "circle-check": "check-circle", "circle-check-regular": "check-circle",
  "circle-info": "info-circle", "circle-question": "question-circle",
  "circle-exclamation": "exclamation-circle", "triangle-exclamation": "exclamation-triangle",
  "message": "chat-square-text", "share-nodes": "share", "share": "share",
  "arrow-right": "arrow-right", "arrow-left": "arrow-left", "arrow-up": "arrow-up",
  "arrow-down": "arrow-down", "arrow-right-long": "arrow-right",
  "arrow-left-long": "arrow-left", "arrow-up-long": "arrow-up",
  "arrow-down-long": "arrow-down", "chevron-right": "chevron-right",
  "chevron-left": "chevron-left", "chevron-up": "chevron-up",
  "chevron-down": "chevron-down", "angle-right": "chevron-right",
  "angle-left": "chevron-left", "angle-up": "chevron-up", "angle-down": "chevron-down",
  "caret-down": "chevron-down", "caret-up": "chevron-up",
  "caret-left": "chevron-left", "caret-right": "chevron-right",
  "rotate": "arrow-repeat", "arrows-rotate": "arrow-repeat", "refresh": "arrow-repeat",
  "download": "download", "upload": "upload", "print": "printer",
  "copy": "files", "clipboard": "clipboard-check", "paste": "clipboard-data",
  "save": "save", "floppy-disk": "save", "file-export": "box-arrow-up-right",
  "file-import": "box-arrow-in-right", "external-link": "box-arrow-up-right",
  "power-off": "power", "plug": "plug", "battery-full": "battery-full",
  "wifi": "wifi", "signal": "wifi", "bluetooth": "bluetooth", "tv": "display",
  "laptop": "laptop", "computer": "display", "mobile-screen": "phone",
  "tablet-screen": "tablet", "server": "server", "database": "database",
  "microchip": "cpu", "memory": "memory", "hard-drive": "hdd",
  "pause": "pause-circle", "stop": "stop-circle", "forward": "forward",
  "backward": "rewind", "volume-high": "volume-up", "volume-low": "volume-down",
  "mute": "volume-mute", "music": "music-note", "headphones": "headset",
  "microphone": "mic", "rss": "rss", "podcast": "mic", "gamepad": "controller",
  "dice": "dice", "puzzle-piece": "puzzle", "wrench": "wrench", "hammer": "hammer",
  "screwdriver-wrench": "tools", "screwdriver": "tools", "robot": "robot",
  "rocket": "rocket-takeoff", "plane": "send", "paper-plane": "send",
  "train": "train-front", "car": "car-front", "bicycle": "bicycle",
  "bus": "bus-front", "truck": "truck", "ship": "ship", "airplane": "send",
  "graduation-cap": "mortarboard", "book": "journal-text", "book-open": "journal-text",
  "newspaper": "newspaper", "pen-nib": "pen", "palette": "palette",
  "paintbrush": "brush", "eraser": "eraser", "ruler": "ruler",
  "magnet": "magnet", "glasses": "glasses", "graduation-cap-regular": "mortarboard",
  "microscope": "microscope", "flask": "flask", "atom": "atom",
  "dna": "dna", "virus": "virus", "heart-pulse": "activity",
  "activity": "activity", "pulse": "activity", "shield": "shield-check",
  "shield-halved": "shield-shaded", "lock-open": "unlock", "fingerprint": "fingerprint",
  "bug": "bug", "broom": "broom", "feather": "feather", "crown": "crown",
  "chess-knight": "chess-knight", "handshake": "handshake", "scale-balanced": "bank",
  "balance-scale": "bank", "gavel": "hammer", "legal": "bank", "school": "mortarboard",
  "chalkboard-user": "person-badge", "chalkboard": "display", "person-chalkboard": "person-badge",
  "seedling": "flower1", "tree": "tree", "mountain": "mountain", "water": "droplet",
  "umbrella": "umbrella", "suitcase-rolling": "briefcase", "basketball": "trophy",
  "futbol": "trophy", "baseball": "trophy", "volleyball": "trophy",
  "heart-crack": "heart", "heart-regular": "heart", "star-regular": "star",
  "square-check": "check-square", "square-check-regular": "check-square",
  "square": "square", "square-plus": "plus-square", "square-minus": "dash-square",
  "thumbs-up": "hand-thumbs-up", "thumbs-down": "hand-thumbs-down",
  "hand": "hand", "hand-pointer": "cursor", "hand-peace": "hand",
  "face-smile": "emoji-smile", "face-frown": "emoji-frown",
  "face-meh": "emoji-neutral", "face-grin": "emoji-laughing",
  "table-cells": "table", "columns": "columns", "bars": "list",
  "bars-staggered": "list-check", "filter": "funnel", "sliders": "sliders",
  "toggle-on": "toggle-on", "toggle-off": "toggle-off", "circle-half-stroke": "circle-half",
  "inbox": "inbox", "outbox": "box-arrow-right", "envelope-open": "envelope-open",
  "phone-volume": "telephone", "mobile": "phone", "id-card": "person-vcard",
  "passport": "person-vcard", "ticket": "ticket-perforated", "qr-code": "qr-code",
  "barcode": "upc-scan", "hourglass": "hourglass-split", "timer": "stopwatch",
  "alarm-clock": "alarm", "bell-regular": "bell", "calendar-day": "calendar-date",
  "calendar-check": "calendar-check", "calendar-xmark": "calendar-x",
  "coins": "coins", "sack-dollar": "cash-stack", "bitcoin-sign": "currency-bitcoin",
  "dollar-sign": "currency-dollar", "euro-sign": "currency-euro",
  "yen-sign": "currency-yen", "pound-sign": "currency-pound",
  "rupee-sign": "currency-rupee", "won-sign": "currency-won",
  "indian-rupee-sign": "currency-rupee", "cny-sign": "currency-yen",
  "hand-holding-dollar": "cash", "chart-simple": "graph-up", "chart-gantt": "bar-chart-steps",
  "chart-scatter": "graph-up", "chart-pie-slice": "pie-chart",
  "warehouse": "building", "factory": "building", "industry": "building",
  "store": "shop", "shop": "shop", "hotel": "building", "hospital": "hospital",
  "heart-pulse": "activity", "stethoscope": "heart-pulse", "syringe": "heart-pulse",
  "bandage": "bandage", "pill": "capsule", "capsules": "capsule",
  "kit-medical": "first-aid", "briefcase-medical": "briefcase",
  "truck-medical": "truck", "fire-extinguisher": "fire", "shield-virus": "shield-check",
  "mask-face": "mask", "head-side-mask": "mask", "lungs": "lungs",
  "brain": "brain", "bone": "bone", "tooth": "tooth",
  "baby": "baby", "child": "child", "person-dress": "person",
  "person-walking": "person-walking", "wheelchair": "person-wheelchair",
  "people-group": "people", "user-plus": "person-plus", "user-minus": "person-dash",
  "user-check": "person-check", "user-xmark": "person-x", "user-gear": "person-gear",
  "user-lock": "person-lock", "user-tie": "person-badge", "user-doctor": "person-badge",
  "user-graduate": "mortarboard", "user-nurse": "person-badge",
  "user-secret": "person", "user-shield": "person-shield",
  "id-badge": "person-vcard", "address-book": "journal-text", "address-card": "person-vcard",
  "building-columns": "bank", "university": "bank", "landmark": "bank",
  "vault": "safe", "box": "box", "boxes-stacked": "boxes", "box-open": "box-seam",
  "cube": "box", "cubes": "boxes", "layer-group": "layers", "diagram-project": "diagram-3",
  "project-diagram": "diagram-3", "sitemap": "diagram-3", "network-wired": "diagram-3",
  "code": "code-slash", "code-regular": "code", "terminal": "terminal",
  "laptop-code": "laptop", "file-code": "file-code", "file-lines": "file-text",
  "file-excel": "file-spreadsheet", "file-powerpoint": "file-ppt", "file-image": "file-image",
  "file-zipper": "file-zip", "file-archive": "file-zip", "file-audio": "file-music",
  "file-video": "file-play", "file-csv": "file-spreadsheet", "file-export": "box-arrow-up-right",
  "file-import": "box-arrow-in-right", "file-pen": "file-edit", "file-circle-plus": "file-plus",
  "folder-plus": "folder-plus", "folder-minus": "folder-minus", "folder-tree": "folder",
  "paperclip-vertical": "paperclip", "link-slash": "link", "unlink": "link",
  "anchor": "anchor", "flag-regular": "flag", "flag-checkered": "flag",
  "bomb": "bomb", "explosion": "boom", "skull": "skull",
  "ghost": "ghost", "spider": "spider", "dragon": "dragon",
  "cat": "cat", "dog": "dog", "paw": "paw", "fish": "fish",
  "crow": "bird", "dove": "bird", "horse": "horse", "hippo": "bug",
  "cow": "bug", "shrimp": "bug", "worm": "bug", "feather-pointed": "feather",
  "earth-asia": "globe-asia-australia", "earth-americas": "globe-americas",
  "earth-europe": "globe-europe-africa", "earth-africa": "globe-europe-africa",
  "earth-oceania": "globe-asia-australia", "globe-regular": "globe",
  "cloud-rain": "cloud-rain", "cloud-bolt": "cloud-lightning-rain", "cloud-showers-heavy": "cloud-rain-heavy",
  "smog": "cloud-fog2", "wind": "wind", "tornado": "tornado", "hurricane": "tornado",
  "rainbow": "rainbow", "icicles": "snow", "temperature-half": "thermometer-half",
  "temperature-high": "thermometer-high", "temperature-low": "thermometer-low",
  "fan": "fan", "plug-circle-bolt": "plug", "plug-circle-xmark": "plug",
  "lightbulb": "lightbulb", "lightbulb-regular": "lightbulb",
  "lightbulb-on": "lightbulb-fill", "flashlight": "lightbulb-fill",
  "battery-quarter": "battery-quarter", "battery-half": "battery-half",
  "battery-three-quarters": "battery-three-quarters", "battery-empty": "battery",
  "battery-bolt": "battery-charging", "battery-exclamation": "battery",
  "plug-circle-check": "plug", "gauge-high": "speedometer", "gauge": "speedometer",
  "tachometer": "speedometer", "gauge-simple": "speedometer", "meteor": "star",
  "satellite": "broadcast", "satellite-dish": "broadcast", "radio": "broadcast",
  "tower-broadcast": "broadcast", "tower-cell": "broadcast", "signal-strong": "wifi",
  "bridge": "building", "road": "signpost", "route-regular": "signpost",
  "traffic-light": "stoplight", "signs-post": "signpost", "sign-hanging": "signpost",
  "sign": "signpost", "milestone": "signpost", "highway": "signpost",
  "truck-fast": "truck", "truck-ramp-box": "truck", "truck-moving": "truck",
  "truck-pickup": "truck", "truck-front": "truck", "van-shuttle": "bus-front",
  "taxi": "car-front", "car-side": "car-front", "car-rear": "car-front",
  "gas-pump": "fuel-pump", "charging-station": "fuel-pump", "oil-can": "fuel-pump",
  "car-battery": "battery-charging", "motorcycle": "bicycle", "scooter": "bicycle",
  "helicopter": "send", "jet-fighter": "send", "rocket-regular": "rocket-takeoff",
  "space-shuttle": "rocket-takeoff", "shuttle-space": "rocket-takeoff",
  "star-of-david": "star-half", "cross": "plus", "church": "building",
  "mosque": "building", "synagogue": "building", "kaaba": "building",
  "hand-holding-heart": "hand", "hand-holding-medical": "hand",
  "hand-holding": "hand", "hands": "hand", "hand-fist": "hand",
  "hand-point-left": "hand-index", "hand-point-right": "hand-index",
  "point-up": "hand-index", "pointer": "cursor", "mouse-pointer": "cursor",
  "arrow-pointer": "cursor", "crosshairs": "bullseye", "bullseye-regular": "bullseye",
  "location-crosshairs": "crosshair", "location-arrow": "send",
  "location-pin": "geo-alt", "map-location-dot": "geo-alt", "map-pin-regular": "pin-map",
  "map-location": "geo-alt", "signs-post-regular": "signpost", "compass-regular": "compass",
  "compass-drafting": "compass", "pencil-regular": "pencil", "pen-regular": "pencil",
  "pen-to-square": "pencil-square", "pen-clip": "pencil", "pen-fancy": "pen",
  "pen-ruler": "pencil-square", "draw-polygon": "hexagon", "bezier-curve": "bezier2",
  "vector-square": "square", "shapes": "shapes", "square-root-variable": "percent",
  "infinity": "infinity", "not-equal": "not-equal", "greater-than": "chevron-right",
  "less-than": "chevron-left", "greater-than-equal": "chevron-right",
  "less-than-equal": "chevron-left", "divide": "dash", "equals": "equal",
  "plus-minus": "plus", "xmark-regular": "x", "check-regular": "check",
  "hashtag": "hash", "at": "at", "quote-left": "quote", "quote-right": "quote",
  "ellipsis": "three-dots", "ellipsis-vertical": "three-dots-vertical",
  "circle-dot": "record-circle", "record-vinyl": "record-circle",
  "dot-circle": "record-circle", "circle-regular": "circle", "circle-half": "circle-half",
  "circle-quarter": "circle", "circle-three-quarters": "circle",
  "circle-notch": "circle", "circle-arrow-right": "arrow-right-circle",
  "circle-arrow-left": "arrow-left-circle", "circle-arrow-up": "arrow-up-circle",
  "circle-arrow-down": "arrow-down-circle", "circle-chevron-right": "arrow-right-circle",
  "circle-chevron-left": "arrow-left-circle", "circle-chevron-up": "arrow-up-circle",
  "circle-chevron-down": "arrow-down-circle", "circle-right": "arrow-right-circle",
  "circle-left": "arrow-left-circle", "circle-up": "arrow-up-circle",
  "circle-down": "arrow-down-circle", "circle-plus": "plus-circle",
  "circle-minus": "dash-circle", "circle-xmark": "x-circle", "circle-regular-regular": "circle",
  "square-xmark": "x-square", "square-poll-vertical": "bar-chart", "square-poll-horizontal": "bar-chart",
  "square-person-confined": "person", "square-caret-down": "caret-down-fill",
  "square-caret-up": "caret-up-fill", "square-caret-left": "caret-left-fill",
  "square-caret-right": "caret-right-fill", "square-full": "square-fill",
  "square-h": "hospital", "square-heart": "heart", "square-check-regular": "check-square",
  "dice-one": "dice-1", "dice-two": "dice-2", "dice-three": "dice-3",
  "dice-four": "dice-4", "dice-five": "dice-5", "dice-six": "dice-6",
  "dice-d6": "dice-6", "dice-d20": "dice-6", "dice-regular": "dice",
  "chess": "chess-knight", "chess-board": "grid", "chess-rook": "chess-knight",
  "chess-queen": "chess-knight", "chess-king": "chess-knight", "chess-bishop": "chess-knight",
  "chess-pawn": "chess-knight", "chess-knight-regular": "chess-knight",
  "building-flag": "building", "building-lock": "building", "building-shield": "building",
  "building-user": "building", "city": "building", "hotel-regular": "building",
  "cart-arrow-down": "cart", "cart-plus": "cart-plus", "cart-flatbed": "cart",
  "gift-card": "gift", "box-regular": "box", "box-open-regular": "box-seam",
  "box-archive": "archive", "archive": "archive", "inbox-regular": "inbox",
  "tray-full": "inbox", "tray-arrow-up": "upload", "tray-arrow-down": "download",
  "cloud-arrow-up": "cloud-arrow-up", "cloud-arrow-down": "cloud-arrow-down",
  "database-arrow-down": "database", "database-arrow-up": "database", "database-check": "database",
  "database-lock": "database", "database-plus": "database-plus", "database-regular-regular": "database",
  "laptop-mobile": "laptop", "mobile-screen-regular": "phone", "mobile-screen-button": "phone",
  "tablet-screen-button": "tablet", "tablet-regular": "tablet", "tv-regular": "display",
  "projector": "display", "film": "film", "clapperboard": "film",
  "circle-play": "play-circle", "play-regular": "play-circle",
  "circle-pause": "pause-circle", "pause-regular": "pause-circle",
  "circle-stop": "stop-circle", "stop-regular": "stop-circle",
  "circle-record": "record-circle", "record-regular": "record-circle",
  "forward-step": "skip-end", "backward-step": "skip-start", "forward-regular": "forward",
  "gauge-simple-high": "speedometer", "gauge-high-regular": "speedometer",
  "phone-slash": "telephone-x", "phone-xmark": "telephone-x", "phone-missed": "telephone",
  "phone-arrow-up-right": "telephone-outbound", "phone-arrow-down-left": "telephone-inbound",
  "broadcast-tower": "broadcast", "broadcast-regular": "broadcast",
  "phone-office": "telephone", "fax": "printer", "print-regular": "printer",
  "clipboard-user": "person-badge", "clipboard-pen": "clipboard-data", "clipboard-question": "clipboard-check",
  "eyedropper": "eyedropper", "pipette": "eyedropper", "paint-roller": "brush",
  "fill": "droplet-fill", "spray-can": "brush", "swatchbook": "palette",
  "pencil-ruler": "pencil-square", "compass-drafting-regular": "compass",
  "ruler-combined": "ruler", "ruler-horizontal": "ruler", "ruler-vertical": "ruler",
  "rotate-left": "arrow-counterclockwise", "rotate-right": "arrow-clockwise",
  "flip-horizontal": "arrow-left-right", "flip-vertical": "arrow-up-down",
  "expand": "arrows-expand", "compress": "arrows-collapse", "maximize": "arrows-fullscreen",
  "minimize": "arrows-fullscreen", "up-right-and-down-left-from-center": "arrows-fullscreen",
  "up-down-left-right": "arrows-move", "arrows-up-down-left-right": "arrows-move",
  "move": "arrows-move", "arrows-up-down": "arrow-up-down", "arrows-left-right": "arrow-left-right",
  "arrows-turn-to-dots": "arrow-repeat", "arrows-spin": "arrow-repeat",
  "arrow-rotate-right": "arrow-clockwise", "arrow-rotate-left": "arrow-counterclockwise",
  "right-left": "arrow-left-right", "left-right": "arrow-left-right",
  "up-down": "arrow-up-down", "down-up": "arrow-up-down",
  "eject": "skip-end", "eject-regular": "skip-end", "power-off-regular": "power",
  "house-chimney-window": "house", "house-crack": "house", "house-fire": "house",
  "house-flag": "house", "house-laptop": "laptop", "house-lock": "house-lock",
  "house-medical-flag": "hospital", "house-signal": "wifi", "house-tree": "house",
  "house-user": "house", "home-regular": "house", "house-regular": "house",
  "person-shelter": "person", "tent": "moon-stars", "tents": "moon-stars",
  "campground": "moon-stars", "fire-regular": "fire", "fire-flame-curved": "fire",
  "fire-flame-simple": "fire", "flame": "fire", "burn": "fire",
  "campfire": "fire", "smoking": "cloud-fog2", "smoking-ban": "ban",
  "cigarette": "cloud-fog2", "no-smoking": "ban", "ban-regular": "ban",
  "cheese": "egg", "pizza-slice": "egg", "burger": "egg", "hotdog": "egg",
  "ice-cream": "egg", "mug-hot": "cup-hot", "mug-saucer": "cup",
  "coffee": "cup", "cup-regular": "cup", "bottle-water": "droplet",
  "glass-water": "droplet", "whiskey-glass": "cup", "martini-glass": "cup",
  "wine-glass": "cup", "champagne-glasses": "cup", "cocktail": "cup",
  "beer-mug-empty": "cup", "mug-regular": "cup", "plate-wheat": "egg",
  "bowl-food": "egg", "utensils": "cup", "fork-knife": "cup",
  "kitchen-set": "cup", "apple-whole": "apple", "apple-regular": "apple",
  "carrot": "carrot", "pepper-hot": "egg", "leafy-green": "flower1",
  "bacon": "egg", "drumstick-bite": "egg", "bone-regular": "bone",
  "person-skull": "skull", "snowman": "snow", "sleigh": "snow",
  "cookie": "egg", "cookie-bite": "egg", "birthday-cake": "cake",
  "cake-candles": "cake", "crown-regular": "crown", "crown-regular-regular": "crown",
  "wand-magic-sparkles": "magic", "wand-sparkles": "magic", "magic-wand-sparkles": "magic",
  "hat-wizard": "magic", "broom-ball": "broom", "broom-regular": "broom",
  "candy": "egg", "lollipop": "egg", "drum": "music-note", "guitar": "music-note",
  "violin": "music-note", "piano": "music-note", "saxophone": "music-note",
  "trumpet": "music-note", "drum-regular": "music-note", "microphone-stand": "mic",
  "headphones-simple": "headset", "ear-listen": "headset", "ear-deaf": "headset",
  "volume-xmark": "volume-mute", "volume-off": "volume-mute", "volume-regular": "volume-up",
  "speaker": "volume-up", "speaker-regular": "volume-up", "waveform": "activity",
  "wave-square": "activity", "heartbeat": "activity", "activity-regular": "activity",
  "star-half-stroke": "star-half", "star-half-regular": "star-half",
  "star-of-life": "star", "staff-snake": "activity", "briefcase-medical-regular": "briefcase",
  "hospital-user": "person-badge", "bed-pulse": "heart-pulse", "syringe-regular": "heart-pulse",
  "prescription": "capsule", "prescription-bottle": "capsule", "prescription-bottle-medical": "capsule",
  "pills": "capsule", "tablets": "capsule", "bandage-regular": "bandage",
  "crutch": "bandage", "cane": "person-walking", "walking": "person-walking",
  "x-ray": "activity", "radiology": "activity", "dna-regular": "dna",
  "vial": "flask", "vials": "flask", "test-tube": "flask",
  "test-tubes": "flask", "beaker": "flask", "flask-vial": "flask",
  "baby-carriage": "baby", "child-regular": "child", "children": "people",
  "people-roof": "people", "person-circle-plus": "person-plus", "person-circle-minus": "person-dash",
  "person-circle-check": "person-check", "person-circle-xmark": "person-x",
  "book-reader": "book", "bookmark-regular": "bookmark-star", "bookmark-regular-regular": "bookmark-star",
  "library": "journal-text", "books": "journal-text", "newspaper-regular": "newspaper",
  "castle": "building", "fort": "building", "person-digging": "person-walking",
  "person-running": "person-walking", "person-biking": "bicycle", "person-swimming": "person-walking",
  "person-hiking": "person-walking", "person-skating": "person-walking",
  "person-snowboarding": "person-walking", "person-skiing": "person-walking",
  "person-skiing-nordic": "person-walking", "person-skiing-slalom": "person-walking",
  "dumbbell": "activity", "basketball-regular": "trophy", "baseball-regular": "trophy",
  "football": "trophy", "rugby": "trophy", "volleyball-regular": "trophy",
  "table-tennis-paddle-ball": "trophy", "tennis-ball": "trophy", "golf-ball-tee": "trophy",
  "bowling-ball": "trophy", "futbol-regular": "trophy", "medal-regular-regular-regular": "award",
  "hourglass-half": "hourglass-split", "hourglass-end": "hourglass",
  "hourglass-start": "hourglass", "timer-regular": "stopwatch", "alarm-clock-regular": "alarm",
  "calendar-minus": "calendar-minus", "calendar-days": "calendar-date", "calendar-week": "calendar-week",
  "calendar-star": "calendar-star", "calendar-minus-regular": "calendar-minus",
  "bell-slash": "bell-slash", "bell-slash-regular": "bell-slash",
  "bell-exclamation": "bell", "bell-ring": "bell-fill", "bell-school": "bell",
  "envelope-circle-check": "envelope-check", "envelope-circle-arrow-right": "envelope",
  "envelope-paper-plane": "send", "paper-plane-regular": "send", "send-regular": "send",
  "share-square": "share", "retweet": "arrow-repeat", "reply-regular": "reply",
  "reply-all": "reply-all", "forward-regular-regular": "forward", "inbox-regular-regular": "inbox",
  "chain": "link-45deg", "link-slash-regular": "link", "unlink-regular": "link",
  "computer-mouse": "mouse", "mouse-regular": "mouse", "print-regular-regular": "printer",
  "file-arrow-down": "file-arrow-down", "file-arrow-up": "file-arrow-up",
  "file-invoice": "file-text", "file-invoice-dollar": "file-text", "file-signature": "file-text",
  "file-contract": "file-text", "file-shield": "file-text", "file-lock": "file-text",
  "file-magnifying-glass": "file-text", "file-magnifying-glass-regular": "file-text",
  "folder-closed": "folder", "folder-closed-regular": "folder", "folder-plus-regular": "folder-plus",
  "folder-video": "folder", "folder-music": "folder", "folder-film": "folder",
  "folder-gear": "folder", "folder-heart": "folder", "folder-tree-regular": "folder",
  "trash-arrow-down": "trash", "trash-can-arrow-up": "trash", "trash-can-arrow-down": "trash",
  "trash-can-clock": "trash", "trash-clock": "trash", "recycle": "arrow-repeat",
  "exclamation": "exclamation-lg", "exclamation-regular": "exclamation-lg",
  "question": "question-lg", "question-regular": "question-lg",
  "info": "info-lg", "info-regular": "info-lg",
  "warning": "exclamation-triangle", "warning-regular": "exclamation-triangle",
  "toilet": "emoji-laughing", "bath": "emoji-laughing", "bath-regular": "emoji-laughing",
  "shower": "droplet", "hands-bubbles": "hand", "soap": "droplet",
  "hand-sparkles": "hand", "hand-holding-droplet": "droplet", "hand-holding-water": "droplet",
  "spa": "flower1", "flower": "flower1", "flower-regular": "flower1",
  "flower-daffodil": "flower1", "flower-tulip": "flower1", "seedling-regular-regular": "flower1",
  "palm-tree": "tree", "palm-tree-regular": "tree", "evergreen": "tree",
  "spruce": "tree", "cactus": "tree", "cactus-regular": "tree",
  "cloud-showers": "cloud-rain", "cloud-showers-heavy-regular": "cloud-rain-heavy",
  "cloud-hail": "cloud-hail", "cloud-snow": "cloud-snow", "cloud-fog": "cloud-fog2",
  "cloud-moon-rain": "cloud-moon", "cloud-regular-regular": "cloud",
  "thermometer": "thermometer-half", "thermometer-empty": "thermometer",
  "thermometer-quarter": "thermometer-quarter", "thermometer-half-regular": "thermometer-half",
  "thermometer-three-quarters": "thermometer-three-quarters", "thermometer-full": "thermometer-high",
  "tint-slash": "droplet", "water-regular": "droplet", "water-arrow-up": "cloud-arrow-up",
  "water-arrow-down": "cloud-arrow-down", "umbrella-regular": "umbrella",
  "umbrella-beach": "umbrella", "parachute-box": "box", "life-ring": "life-preserver",
  "anchor-circle-check": "anchor", "anchor-circle-exclamation": "anchor",
  "anchor-circle-xmark": "anchor", "anchor-lock": "anchor", "sailboat": "ship",
  "person-ferry": "ship", "anchor-regular-regular": "anchor", "binoculars": "binoculars",
  "flag-pennant": "flag", "flag-usa": "flag", "flag-regular-regular-regular": "flag",
  "clapperboard-play": "film", "tower-control": "broadcast", "sitemap-regular": "diagram-3",
  "diagram-successor": "diagram-3", "network-wired-regular": "diagram-3",
  "clock-rotate-left": "clock-history", "history": "clock-history",
  "right-to-bracket": "box-arrow-in-right", "left-to-bracket": "box-arrow-in-left",
  "right-from-bracket": "box-arrow-right", "left-from-bracket": "box-arrow-left",
  "sign-in": "box-arrow-in-right", "sign-out": "box-arrow-right",
  "sign-in-alt": "box-arrow-in-right", "sign-out-alt": "box-arrow-right",
  "arrow-right-to-bracket": "box-arrow-in-right", "arrow-left-from-bracket": "box-arrow-left",
  "arrow-up-from-bracket": "box-arrow-up", "arrow-down-to-bracket": "box-arrow-in-down",
  "people-arrows": "people", "people-carry-box": "people", "people-pulling": "people",
  "people-robbery": "people", "people-line": "people", "person-arrow-up-from-line": "person",
  "person-arrow-down-to-line": "person", "person-arrow-up-right-from-square": "person",
  "person-arrow-down-right-from-square": "person", "person-booth": "person",
  "person-cane": "person", "person-carry-box": "person", "person-chalkboard-regular": "person-badge",
  "person-circle-info": "person", "person-circle-minus-regular": "person-dash",
  "person-dolly-empty": "person", "person-dots-from-line": "person",
  "person-dress-burst": "person", "person-exclamation": "person", "person-falling": "person",
  "person-falling-burst": "person", "person-half-dress": "person", "person-harassing": "person",
  "person-military-pointing": "person", "person-military-rifle": "person",
  "person-military-to-person": "person", "person-pin": "person", "person-rays": "person",
  "person-rifle": "person", "person-seat": "person", "person-seat-reclined": "person",
  "person-sign": "person", "person-simple": "person", "person-standing": "person",
  "person-snowmobiling": "person-walking", "person-stairs": "person",
  "person-through-window": "person", "person-walking-arrow-loop-left": "person-walking",
  "person-walking-arrow-right": "person-walking", "person-walking-dashed-line-arrow-right": "person-walking",
  "person-walking-luggage": "person-walking", "person-wheelchair-move": "person-wheelchair",
  "tent-arrow-left-right": "moon-stars", "tent-arrow-turn-left": "moon-stars",
  "tent-arrows-down": "moon-stars", "tent-regular": "moon-stars", "tents-regular": "moon-stars",
  "house-chimney-medical": "hospital", "house-chimney-user": "house",
  "house-circle-check": "house", "house-circle-exclamation": "house",
  "house-circle-xmark": "house", "house-crack-regular-regular": "house",
  "school-circle-exclamation": "mortarboard", "school-circle-xmark": "mortarboard",
  "school-flag": "mortarboard", "school-lock-regular": "mortarboard",
  "money-bill-wave": "cash", "money-bill-wave-regular": "cash", "money-bill-transfer": "cash",
  "money-bill-trend-up": "graph-up-arrow", "money-bill-wheat": "cash", "money-check": "cash",
  "money-check-dollar": "cash", "money-check-dollar-regular": "cash", "money-check-regular": "cash",
  "hand-holding-usd": "cash", "hand-holding-circle-dollar": "cash",
  "popcorn": "egg", "bomb-regular": "bomb", "explosion-regular": "boom",
  "burst": "boom", "burst-regular": "boom", "mound": "mountain",
  "mountain-city": "mountain", "mountain-sun-regular": "mountain", "mountain-regular-regular": "mountain",
  "thermal": "thermometer-half", "mug-marshmallows": "cup-hot", "mug-regular-regular": "cup",
  "glass-water-droplet": "droplet", "wine-glass-regular": "cup", "whiskey-glass-regular": "cup",
  "bowl-rice": "egg", "bowl-regular": "egg", "plate-wheat-regular": "egg",
  "jar": "cup", "jar-wheat": "cup", "bottle-droplet": "droplet", "bottle-regular": "droplet",
  "jug-detergent": "droplet", "pump-soap": "droplet", "hand-holding-droplet-regular": "droplet",
  "trash-can-xmark": "trash", "trash-can-undo": "trash", "trash-undo": "trash",
  "arrow-down-to-water": "cloud-arrow-down", "water-ladder": "droplet",
  "wind-warning": "cloud-fog2", "wind-circle-exclamation": "cloud-fog2",
  "plug-circle-minus": "plug", "plug-circle-plus": "plug", "plug-circle-xmark-regular": "plug",
  "bolt-lightning": "lightning-charge", "bolt-regular-regular": "lightning-charge",
  "shooting-star": "star", "shooting-star-regular": "star", "comet": "star",
  "circle-small": "circle", "square-full-regular": "square-fill", "square-regular-regular-regular": "square",
  "manat-sign": "currency-dollar", "nisisign": "currency-dollar", "shekel-sign": "currency-dollar",
  "baht-sign": "currency-dollar", "rial-sign": "currency-dollar", "lira-sign": "currency-dollar",
  "hryvnia-sign": "currency-dollar", "tenge-sign": "currency-dollar", "guarani-sign": "currency-dollar",
  "austral-sign": "currency-dollar", "cedi-sign": "currency-dollar", "colon-sign": "currency-dollar",
  "cruzeiro-sign": "currency-dollar", "dong-sign": "currency-dollar", "florin-sign": "currency-dollar",
  "franc-sign": "currency-dollar", "kips-sign": "currency-dollar", "kip-sign": "currency-dollar",
  "ruble-sign": "currency-dollar", "sign-hanging-regular": "signpost", "signs-post-regular-regular": "signpost",
  "bridge-circle-exclamation": "building", "bridge-circle-xmark": "building",
  "bridge-lock": "building", "bridge-water": "building", "bridge-regular-regular": "building",
  "traffic-light-go": "stoplight", "traffic-light-regular-regular": "stoplight",
  "arrow-trend-up": "graph-up-arrow", "arrow-trend-down": "graph-down",

};

/**
 * 解析官方 iconName（"style:name"）→ 本地 Bootstrap 图标 key（ICONS）。
 * @param {string} iconName
 * @returns {string|null} ICONS 的 key；未知返回 null（渲染占位、导出跳过）
 */
export function resolveIconName(iconName) {
  if (typeof iconName !== "string" || !iconName) return null;
  const idx = iconName.indexOf(":");
  if (idx < 0) return null; // 官方格式必须带 style 前缀（fas:/far:/fab:/bs:）
  const style = iconName.slice(0, idx).toLowerCase();
  const name = iconName.slice(idx + 1);
  if (style === "fas" || style === "far" || style === "fab") {
    return FA_TO_BS[name] || null;
  }
  // bs: 或其他命名空间 → 直接查本地库
  return ICONS[name] ? name : null;
}
