// ============================================================================
// model/icon-fa.js — Font Awesome icon registry and resolution (fas/far/fab, official PPTD spec)
// ----------------------------------------------------------------------------
// The registry assets/icons/registry.json is generated by scripts/gen-icon-registry.mjs;
// the SVG bodies are not committed (assets/icons/<style>/<name>.svg, fetched by
// `icons download` or from a CDN).
// Same dual-environment pattern as font-registry.js:
//   - loadIconRegistry(options): Node uses {iconDir, fs} injection, the browser fetches
//     relative to ROOT; module-level singleton cache
//   - resolveIconName(iconName, registry) -> hit {name, prefix, dir, w, h} | null
//     (prefix maps to the directory; names are normalized through aliases, e.g. home->house;
//     style availability is validated)
//   - fetchIconSvg(hit, registry): browser source chain Cache API -> local -> jsDelivr -> unpkg
//   - loadIconSvgNode(hit, registry, {iconDir, fs}): CLI/Node reads the local library first, CDN as fallback
//   - normalizeIconSvg(text, hit) -> {inner, w, h} (strips the root svg/comments and
//     fill="currentColor" so paths inherit the injected fill)
// ============================================================================

const REGISTRY_REL = "assets/icons/registry.json";
const ROOT = new URL("../../", import.meta.url).href;

/** Prefix <-> classic-family SVG directory. */
export const STYLE_DIRS = { fas: "solid", far: "regular", fab: "brands" };

/** CDN sources (jsDelivr primary + unpkg mirror), matching `icons download`. */
export function faCdnUrls(faVersion, hit) {
  const path = `@fortawesome/fontawesome-free@${faVersion}/svgs/${hit.dir}/${hit.name}.svg`;
  return [`https://cdn.jsdelivr.net/npm/${path}`, `https://unpkg.com/${path}`];
}

// ---------------------------------------------------------------------------
// Registry loading (dual environment, singleton cache)
// ---------------------------------------------------------------------------

let cachedRegistry = null;

/**
 * @param {object} [options] Node passes { iconDir, fs:{readFileSync} };
 *   registryDir can override the registry directory (once resources are externalized the
 *   registry stays in the package and may be separate from the font directory); the browser
 *   passes nothing (fetches registry.json relative to ROOT).
 */
export async function loadIconRegistry(options = {}) {
  if (cachedRegistry) return cachedRegistry;
  if (options.iconDir && options.fs?.readFileSync) {
    // Path concatenation as a string (zero dependencies: the model layer may not import node:, see the dep-graph rules)
    const base = String(options.registryDir || options.iconDir).replace(/\\/g, "/").replace(/\/+$/, "");
    cachedRegistry = JSON.parse(options.fs.readFileSync(`${base}/registry.json`, "utf8"));
  } else {
    const res = await fetch(new URL(REGISTRY_REL, ROOT).href);
    if (!res.ok) throw new Error(`icon registry HTTP ${res.status}`);
    cachedRegistry = await res.json();
  }
  return cachedRegistry;
}

// ---------------------------------------------------------------------------
// Name resolution (with alias normalization; the index is cached per registry instance)
// ---------------------------------------------------------------------------

const indexCache = new WeakMap();

/** name -> entry primary index + alias -> entry alias index (an alias only points at the primary name). */
function indexOf(registry) {
  let idx = indexCache.get(registry);
  if (!idx) {
    idx = { byName: new Map(), byAlias: new Map() };
    for (const entry of registry.icons) {
      idx.byName.set(entry.name, entry);
      for (const a of entry.aliases || []) idx.byAlias.set(a, entry);
    }
    indexCache.set(registry, idx);
  }
  return idx;
}

/**
 * Official iconName "style:name" -> matching entry; illegal format / unknown name / prefix not available -> null.
 * @returns {{name, prefix, dir, w, h}} normalized name (aliases normalized to the primary name).
 */
export function resolveIconName(iconName, registry) {
  if (!iconName || !registry) return null;
  const i = String(iconName).indexOf(":");
  if (i <= 0) return null;
  const prefix = iconName.slice(0, i);
  const dir = STYLE_DIRS[prefix];
  if (!dir) return null;
  const raw = iconName.slice(i + 1);
  const { byName, byAlias } = indexOf(registry);
  const entry = byName.get(raw) || byAlias.get(raw);
  if (!entry || !entry.styles.includes(prefix)) return null;
  return { name: entry.name, prefix, dir, w: entry.w, h: entry.h };
}

// ---------------------------------------------------------------------------
// SVG fetching and normalization
// ---------------------------------------------------------------------------

const ICON_CACHE = "open-pptd-icons-v1";
const cacheKey = (url, v) => `${url}?v=${v}`;

/** Browser side: Cache API -> local -> CDN chain; returns null when all fail. */
export async function fetchIconSvg(hit, registry) {
  const localUrl = new URL(`assets/icons/${hit.dir}/${hit.name}.svg`, ROOT).href;
  const urls = [localUrl, ...faCdnUrls(registry.faVersion, hit)];
  try {
    const cache = await caches.open(ICON_CACHE);
    for (const url of urls) {
      const cached = await cache.match(cacheKey(url, registry.faVersion));
      if (cached) return await cached.text();
    }
  } catch { /* Cache API unavailable (private mode etc.) -> skip the cache layer */ }
  for (const url of urls) {
    try {
      const res = await fetch(url);
      if (!res.ok) continue;
      const text = await res.text();
      try {
        const cache = await caches.open(ICON_CACHE);
        await cache.put(cacheKey(url, registry.faVersion), new Response(text));
      } catch { /* a failed cache write does not block */ }
      return text;
    } catch { /* network failure -> try the next source */ }
  }
  return null;
}

/** Node side (CLI export/check): read the local library directly -> CDN fetch fallback; null = absent on both sides. */
export async function loadIconSvgNode(hit, registry, env = {}) {
  if (env.iconDir && env.fs?.readFileSync) {
    try {
      const base = String(env.iconDir).replace(/\\/g, "/").replace(/\/+$/, "");
      return env.fs.readFileSync(`${base}/${hit.dir}/${hit.name}.svg`, "utf8");
    } catch { /* local file missing -> fall through to the CDN */ }
  }
  for (const url of faCdnUrls(registry.faVersion, hit)) {
    try {
      const res = await fetch(url);
      if (res.ok) return await res.text();
    } catch { /* try the next mirror */ }
  }
  return null;
}

/**
 * FA raw SVG -> {inner, w, h, vx, vy}: strips the root <svg> tag and the copyright comment,
 * and removes fill="currentColor" (an explicit currentColor on FA paths would bypass the root
 * fill we inject, so it must be stripped for the paths to inherit).
 * viewBox semantics: some FA 7 icon paths extend beyond the declared box (fire/bolt etc.
 * contain negative coordinates) and SVG clips by default -> the tip gets cut. Content-aware
 * expansion is done here: when out of bounds, vx/vy become non-zero and w/h grow accordingly,
 * keeping the icon whole (the caller outputs viewBox="${vx} ${vy} ${w} ${h}").
 */
export function normalizeIconSvg(text, hit = null) {
  const m = text && text.match(/<svg[^>]*>([\s\S]*)<\/svg>/);
  if (!m) return null;
  let w = hit?.w, h = hit?.h;
  if (!w || !h) {
    const vb = text.match(/viewBox="([-\d.]+) ([-\d.]+) ([-\d.]+) ([-\d.]+)"/);
    if (!vb) return null;
    w = Number(vb[3]);
    h = Number(vb[4]);
  }
  const inner = m[1].replace(/<!--[\s\S]*?-->/g, "").replace(/\sfill="currentColor"/g, "").trim();
  if (!inner) return null;
  const expanded = expandViewBox(inner, w, h);
  if (expanded) {
    const [vx, vy, ew, eh] = expanded;
    return { inner, w: ew, h: eh, vx, vy };
  }
  return { inner, w, h, vx: 0, vy: 0 };
}

// ---------------------------------------------------------------------------
// Path out-of-bounds detection and viewBox expansion
// ----------------------------------------------------------------------------
// Some FA 7 icon paths extend outside the declared viewBox (e.g. fire starts at y=-26.4),
// while the SVG root clips content outside the viewBox by default -> flame/bolt tips get
// flattened (browser and PowerPoint are affected alike).
// Fast path: scan whether absolutized coordinates fall inside the declared box (the vast
// majority of icons do not overflow, zero cost);
// Slow path: exact Bezier bounds (extrema = endpoints + derivative roots), expanding the
// viewBox until it fully contains the content.
// ----------------------------------------------------------------------------

/** Path command tokenizer (FA paths use the M/L/H/V/C/S/Q/T/A/Z subset). */
function tokenizePath(d) {
  return String(d).match(/[a-zA-Z]|-?\.?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?/g) || [];
}

/** Content bounding box (including cubic-curve extrema: derivative roots; arc A is conservatively bounded by its endpoints, FA paths rarely use it). */
export function pathBBox(d) {
  const t = tokenizePath(d);
  let i = 0, x = 0, y = 0, sx = 0, sy = 0;
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  const push = (px, py) => {
    if (px < minX) minX = px;
    if (py < minY) minY = py;
    if (px > maxX) maxX = px;
    if (py > maxY) maxY = py;
  };
  /** Extrema of a cubic curve in both dimensions (quadratic derivative roots; a root inside (0,1) contributes to the bbox). */
  function sampleDims(dims, emit) {
    for (let dim = 0; dim < 2; dim++) {
      const [p0, p1, p2, p3] = dims[dim];
      const a = 3 * (-p0 + 3 * p1 - 3 * p2 + p3);
      const b = 6 * (p0 - 2 * p1 + p2);
      const c = 3 * (p1 - p0);
      const roots = [];
      if (Math.abs(a) < 1e-9) {
        if (Math.abs(b) > 1e-9) roots.push(-c / b);
      } else {
        const disc = b * b - 4 * a * c;
        if (disc >= 0) {
          const sq = Math.sqrt(disc);
          roots.push((-b + sq) / (2 * a), (-b - sq) / (2 * a));
        }
      }
      for (const r of roots) {
        if (r > 0 && r < 1) {
          const v = p0 * (1 - r) ** 3 + 3 * p1 * r * (1 - r) ** 2 + 3 * p2 * r ** 2 * (1 - r) + p3 * r ** 3;
          emit(v, dim === 0);
        }
      }
    }
  }

  const num = () => parseFloat(t[i++]);
  let prevCx = null, prevCy = null, prevQx = null, prevQy = null; // reflection state for C/S and Q/T
  while (i < t.length) {
    const cmd = t[i];
    if (/[\d.]/.test(cmd)) { i++; continue; } // defensive: skip stray numbers (command-driven parsing is enough)
    i += 1;
    if (cmd === "Z" || cmd === "z") { x = sx; y = sy; continue; }
    const rel = cmd >= "a" && cmd <= "z";
    if (cmd.toLowerCase() === "m") { prevCx = prevCy = prevQx = prevQy = null; } // M resets the reflection state
    switch (cmd.toLowerCase()) {
      case "m": {
        let px = num(), py = num();
        if (rel) { px += x; py += y; }
        x = sx = px; y = sy = py; push(x, y);
        // subsequent implicit coordinate pairs are treated as L
        while (i < t.length && /[\d.]/.test(t[i])) {
          let lx = num(), ly = num();
          if (rel) { lx += x; ly += y; }
          x = lx; y = ly; push(x, y);
        }
        break;
      }
      case "l": {
        while (i < t.length && /[\d.]/.test(t[i])) {
          let px = num(), py = num();
          if (rel) { px += x; py += y; }
          x = px; y = py; push(x, y);
        }
        break;
      }
      case "h": {
        while (i < t.length && /[\d.]/.test(t[i])) {
          let px = num();
          if (rel) px += x;
          x = px; push(x, y);
        }
        break;
      }
      case "v": {
        while (i < t.length && /[\d.]/.test(t[i])) {
          let py = num();
          if (rel) py += y;
          y = py; push(x, y);
        }
        break;
      }
      case "c":
      case "s": {
        // C gives both control points explicitly; for S the first control point is the reflection of the previous C/S control point about the current point
        do {
          let x1, y1, x2, y2, px, py;
          if (cmd.toLowerCase() === "c") {
            x1 = num(); y1 = num(); x2 = num(); y2 = num(); px = num(); py = num();
            if (rel) { x1 += x; y1 += y; x2 += x; y2 += y; px += x; py += y; }
          } else {
            x1 = 2 * x - (prevCx ?? x); y1 = 2 * y - (prevCy ?? y);
            x2 = num(); y2 = num(); px = num(); py = num();
            if (rel) { x2 += x; y2 += y; px += x; py += y; }
          }
          sampleDims([[x, x1, x2, px], [y, y1, y2, py]], (v, isX) => (isX ? push(v, y) : push(x, v)));
          prevCx = x2; prevCy = y2;
          x = px; y = py; push(x, y);
        } while (i < t.length && /[\d.]/.test(t[i]));
        break;
      }
      case "q":
      case "t": {
        // Q gives an explicit control point; T is implicit = reflection of the previous Q/T control point. A quadratic extremum = root of the first derivative
        do {
          let qx, qy, px, py;
          if (cmd.toLowerCase() === "q") {
            qx = num(); qy = num(); px = num(); py = num();
            if (rel) { qx += x; qy += y; px += x; py += y; }
          } else {
            qx = 2 * x - (prevQx ?? x); qy = 2 * y - (prevQy ?? y);
            px = num(); py = num();
            if (rel) { px += x; py += y; }
          }
          const dims = [[x, qx, px], [y, qy, py]];
          for (let dim = 0; dim < 2; dim++) {
            const [p0, p1, p2] = dims[dim];
            const denom = p0 - 2 * p1 + p2;
            if (Math.abs(denom) > 1e-9) {
              const r = (p0 - p1) / denom;
              if (r > 0 && r < 1) {
                const v = p0 * (1 - r) ** 2 + 2 * p1 * r * (1 - r) + p2 * r ** 2;
                dim === 0 ? push(v, y) : push(x, v);
              }
            }
          }
          prevQx = qx; prevQy = qy;
          x = px; y = py; push(x, y);
        } while (i < t.length && /[\d.]/.test(t[i]));
        break;
      }
      case "a": {
        // Arc: endpoints plus a conservative radius bound (FA paths rarely use A)
        do {
          num(); num(); num(); // rx ry rot
          num(); num();        // laf sf
          let px = num(), py = num();
          if (rel) { px += x; py += y; }
          x = px; y = py; push(x, y);
        } while (i < t.length && /[\d.]/.test(t[i]));
        break;
      }
      default:
        // unknown command: stop parsing (conservatively return the bounds collected so far)
        i = t.length;
    }
  }
  if (!isFinite(minX)) return null;
  return { minX, minY, maxX, maxY };
}

/**
 * Expand the viewBox when the content is out of bounds: returns [x, y, w, h] (union of the
 * declared box and the content box). Returns null when nothing is out of bounds (the caller
 * keeps the declared box, zero-cost path).
 * inner is the full content including <path> tags — only the d attributes are used for bounds.
 */
export function expandViewBox(inner, w, h) {
  const ds = String(inner).match(/\bd="([^"]*)"/g) || [];
  if (!ds.length) return null;
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  for (const attr of ds) {
    const bb = pathBBox(attr.slice(3, -1));
    if (!bb) continue;
    minX = Math.min(minX, bb.minX); minY = Math.min(minY, bb.minY);
    maxX = Math.max(maxX, bb.maxX); maxY = Math.max(maxY, bb.maxY);
  }
  if (!isFinite(minX)) return null;
  if (minX >= -0.01 && minY >= -0.01 && maxX <= w + 0.01 && maxY <= h + 0.01) return null;
  const x0 = Math.min(0, Math.floor(minX * 10) / 10);
  const y0 = Math.min(0, Math.floor(minY * 10) / 10);
  const x1 = Math.max(w, Math.ceil(maxX * 10) / 10);
  const y1 = Math.max(h, Math.ceil(maxY * 10) / 10);
  return [x0, y0, Math.round((x1 - x0) * 10) / 10, Math.round((y1 - y0) * 10) / 10];
}
