// ============================================================================
// pptd-io.js — PPTD YAML <-> unified data model (lenient parse / subset serialize)
// ----------------------------------------------------------------------------
// Opening a full PPTD project generated by Kimi uses "lenient parsing": every
// recognized field is read, unrecognized fields are kept verbatim in el.extra (so
// writing back loses as little information as possible); the editor, however,
// only promises to support this project's component subset (see model.js).
// ============================================================================

import * as yaml from "./vendor/js-yaml.mjs";
import { createDeck, createPage, deckSize } from "./model.js";
import { normalizeCells } from "./table.js";

/**
 * Parse a PPTD project (manifest + pages) -> unified deck model.
 * @param {string} manifestYaml .pptd file text
 * @param {Map<string,string>} pageFiles page path -> file text
 * @param {object} [options] { basePath } used to resolve relative paths
 */
export function parseDeck(manifestYaml, pageFiles = new Map(), options = {}) {
  const manifest = yaml.load(manifestYaml);
  if (!manifest || typeof manifest !== "object" || Array.isArray(manifest)) {
    throw new Error("无效的 PPTD manifest（顶层应为映射）");
  }
  if (manifest.version !== "v2") {
    console.warn(`[pptd-io] 未知版本 ${manifest.version}，按 v2 尝试解析`);
  }

  const deck = createDeck({
    title: manifest.title,
    size: deckSize(manifest),
    theme: manifest.theme || null,
    fonts: manifest.fonts || null,
  });
  deck.extra = pickExtra(manifest, ["version", "title", "size", "theme", "fonts", "pages"]);

  const pages = Array.isArray(manifest.pages) ? manifest.pages : [];
  for (const rel of pages) {
    const text = pageFiles.get(String(rel));
    if (text == null) {
      console.warn(`[pptd-io] 缺少页面文件 ${rel}，已跳过`);
      continue;
    }
    let page;
    try {
      page = parsePage(text);
    } catch (err) {
      // A single page failing to parse -> degrade to an error placeholder page
      // (the renderer shows a red box) instead of aborting the whole project load
      console.warn(`[pptd-io] 页面 ${rel} 解析失败，已降级为错误占位页: ${err.message}`);
      page = createPage({ pageType: "content" });
      page._parseError = err.message || String(err);
      page._parseErrorLine = err.mark && typeof err.mark.line === "number" ? err.mark.line + 1 : null;
      page._rawText = text; // keep the raw text and write it back verbatim on save, losing nothing
    }
    page._path = String(rel);
    deck.pages.push(page);
  }
  return deck;
}

function parsePage(text) {
  const data = yaml.load(text);
  if (!data || typeof data !== "object" || Array.isArray(data)) {
    throw new Error("无效的 page 文件（顶层应为映射）");
  }
  const page = createPage({
    pageType: typeof data.pageType === "string" ? data.pageType : "content",
    background: data.background || null,
    notes: typeof data.notes === "string" ? data.notes : "",
  });
  page.extra = pickExtra(data, ["pageType", "background", "notes", "elements"]);
  page.elements = (Array.isArray(data.elements) ? data.elements : [])
    .map((el, i) => normalizeElement(el, i))
    .filter(Boolean);
  return page;
}

function normalizeElement(el, index) {
  if (!el || typeof el !== "object" || Array.isArray(el)) {
    console.warn(`[pptd-io] 忽略无效元素 #${index}`);
    return null;
  }
  if (typeof el.elementId !== "string" || !el.elementId) {
    el.elementId = `el${index + 1}`;
  }
  if (!Array.isArray(el.bounds) || el.bounds.length !== 4) {
    console.warn(`[pptd-io] 元素 ${el.elementId} bounds 无效，已跳过`);
    return null;
  }
  // Lenient: keep unknown fields (used when writing back)
  const known = ["elementId", "elementType", "bounds", "rotation", "opacity", "flip"];
  el.extra = pickExtra(el, known);
  // Table compatibility: bare-value cells (string/number) -> {text: value}, so consumers only read cell.text
  if (el.elementType === "table" && Array.isArray(el.rows)) {
    el.rows = normalizeCells(el.rows);
  }
  return el;
}

function pickExtra(obj, known) {
  const extra = {};
  for (const key of Object.keys(obj)) {
    if (!known.includes(key)) extra[key] = obj[key];
  }
  return extra;
}

/**
 * Serialize the unified deck model into PPTD (subset).
 * @param {object} deck
 * @param {object} [options] { manifestName } manifest file name (default deck.pptd)
 * @returns {Array<{path:string, content:string}>} manifest + pages file list
 */
export function serializeDeck(deck, options = {}) {
  // Unknown fields kept by lenient parsing (deck/page level extra) are merged back
  // on write so nothing is lost; known fields take precedence
  const manifest = {
    ...(deck.extra || {}),
    version: "v2",
    title: deck.title,
    size: deck.size,
  };
  if (deck.theme) manifest.theme = deck.theme;
  if (deck.fonts) manifest.fonts = deck.fonts;
  const manifestName = options.manifestName || "deck.pptd";
  manifest.pages = deck.pages.map((p, i) => p._path || `pages/${i + 1}.page`);

  const files = [{ path: manifestName, content: yaml.dump(manifest) }];
  deck.pages.forEach((page, i) => {
    const data = {
      ...(page.extra || {}),
      pageType: page.pageType || "content",
      // Element-level unknown fields (el.extra) are spread back to the element top
      // level on write, leaving no nested extra key
      elements: (page.elements || []).map((el) => {
        if (!el || !el.extra || Object.keys(el.extra).length === 0) return el;
        const { extra, ...rest } = el;
        return { ...extra, ...rest };
      }),
    };
    if (page.background) data.background = page.background;
    if (page.notes) data.notes = page.notes;
    const path = page._path || `pages/${i + 1}.page`;
    // Failed-parse page: write the raw text back verbatim so editor serialization
    // cannot damage the original content
    const content = page._rawText != null ? page._rawText : yaml.dump(data);
    files.push({ path, content });
  });
  return files;
}
