// ============================================================================
// server/index.js — open-pptd local server (assembly root)
// ----------------------------------------------------------------------------
// Zero dependencies (Node built-in http). Responsibilities split by file:
//   static.js    static file serving (MIME + traversal-safe resolution)
//   api.js       /api/save write-back, /api/ping liveness probe
//   events.js    /events SSE change push (directory fingerprint polling)
//   gallery.js   /examples/manifest.json dynamic gallery index
// Public interface (createServer/startServer signatures, endpoints, SSE protocol)
// is unchanged from earlier versions.
// Optional virtual mount: --project <dir> mounts any local project under
// /project/ for browser preview.
// ============================================================================

import http from "node:http";
import { existsSync } from "node:fs";
import { join, normalize, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { resolveFile, resolveStaticFile, sendFile } from "./static.js";
import { resourceRoots as DEFAULT_RESOURCE_ROOTS } from "../paths.js";
import { handleSave, handlePing } from "./api.js";
import { createExportImageHandler } from "./export-image.js";
import { createSseHub } from "./events.js";
import { buildManifest } from "./gallery.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
export const PROJECT_ROOT = join(__dirname, "..", "..");

export function createServer(options = {}) {
  const root = normalize(options.root || PROJECT_ROOT);
  // Externalized resources: /assets/** resolves across multiple roots (home first,
  // then package fallback; registry is package-only). Defaults to resourceRoots from
  // packages/paths.js; downstream may inject its own roots.
  const resourceRoots = options.resourceRoots || DEFAULT_RESOURCE_ROOTS;
  // Optional virtual mount: /project/<path> → real file under projectRoot (--project <dir>)
  const projectRoot = options.projectRoot ? normalize(resolve(options.projectRoot)) : null;
  // liveReload:false is for one-shot render temp servers (no SSE polling, so the
  // directory can be safely removed after export).
  const sse = projectRoot && options.liveReload !== false ? createSseHub(projectRoot) : null;
  // Image export endpoint (RP-C / M5): capture-first — GET probes the browser,
  // POST renders headless. The handler shares this module's origin; startServer is
  // injected here (renderDeck needs a temporary static server).
  const exportImage = createExportImageHandler({ startServer });

  return http.createServer((req, res) => {
    try {
      const url = new URL(req.url, "http://127.0.0.1");
      let pathname = decodeURIComponent(url.pathname);
      let base = root;
      if (projectRoot && (pathname === "/project" || pathname.startsWith("/project/"))) {
        base = projectRoot;
        pathname = pathname === "/project" ? "/" : pathname.slice("/project".length);
      }
      // SSE change push: only with --project mount
      if (pathname === "/events" && sse) {
        sse.handle(req, res);
        return;
      }
      // Write-back API: only with --project mount
      if (pathname === "/api/save" && req.method === "POST") {
        handleSave(req, res, projectRoot);
        return;
      }
      // Liveness API: local serve only (404 on GitHub Pages)
      if (pathname === "/api/ping") {
        handlePing(res);
        return;
      }
      // Image export (capture-first): GET = capability probe, POST = headless render (RP-C / M5)
      if (pathname === "/api/export-image") {
        exportImage(req, res).catch((err) => {
          try {
            res.writeHead(500, { "Content-Type": "application/json; charset=utf-8" }).end(JSON.stringify({ ok: false, error: String(err?.message || err) }));
          } catch {
            /* response already ended */
          }
        });
        return;
      }
      // Gallery index: generated by scanning examples/ dynamically (drop a folder in
      // and it shows up; the static manifest.json on disk is only for GitHub Pages,
      // local always uses dynamic scan)
      if (pathname === "/examples/manifest.json") {
        const examplesDir = join(root, "examples");
        if (existsSync(examplesDir)) {
          res.writeHead(200, { "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store" });
          res.end(JSON.stringify(buildManifest(examplesDir)));
        } else {
          res.writeHead(404).end("no examples");
        }
        return;
      }
      // Resource request (/assets/**) → multi-root resolution (home first, then package fallback; registry is package-only)
      let filePath = null;
      if (pathname.startsWith("/assets/")) {
        filePath = resolveStaticFile(pathname, resourceRoots) || resolveFile(base, pathname);
      } else {
        // Directory path → index.html inside (same as GitHub Pages: <root>/index.html is the gallery)
        filePath = resolveFile(base, pathname);
        if (!filePath && pathname.endsWith("/")) {
          filePath = resolveFile(base, pathname + "index.html");
        }
      }
      if (!filePath) {
        res.writeHead(404).end("not found: " + pathname);
        return;
      }
      sendFile(res, filePath);
    } catch (err) {
      res.writeHead(500).end(String(err?.stack || err));
    }
  });
}

export function startServer(options = {}) {
  const basePort = options.port ?? 55173; // port: 0 = random free port
  return new Promise((resolve, reject) => {
    const tryListen = (port) => {
      const server = createServer(options);
      server.once("error", (err) => {
        // Auto-increment on a busy port (up to 10 tries); no manual port change
        if (err?.code === "EADDRINUSE" && port - basePort < 10) {
          tryListen(port + 1);
        } else {
          reject(err);
        }
      });
      server.listen(port, "127.0.0.1", () => {
        // port: 0 = random free port (one-shot scenarios such as render); actual port comes from address()
        const actualPort = server.address().port;
        const base = `http://127.0.0.1:${actualPort}/`;
        // Editor entry lives at /editor/ (root is the gallery; ?deck= is not handled there)
        const info = {
          server,
          port: actualPort,
          url: options.deckUrl ? base + "editor/?deck=" + options.deckUrl : base + "editor/",
        };
        // When onListen is injected the caller decides the output channel (serve --json requires human text on stderr)
        if (typeof options.onListen === "function") options.onListen(info);
        else console.log(`open-pptd 已启动: ${info.url}`);
        resolve(server);
      });
    };
    tryListen(basePort);
  });
}
