#!/usr/bin/env node
// ============================================================================
// formula.mjs — MathML→OMML byte-level regression
// ----------------------------------------------------------------------------
// Usage: node tests/regression/formula.mjs [--verbose]
// Compares the output of packages/model/mathml2omml.js against frozen references
// produced by Microsoft's official MML2OMML.XSL (tests/fixtures/formula/omml-ai/);
// a character-exact match is required.
//
// Corpus: tests/fixtures/formula/formulas.txt (204 LaTeX cases)
//         mml/     KaTeX output (generated by tests/tools/dump-formula-mml.mjs, not committed)
//         omml-ai/ frozen official XSLT references (batch-generated via Office MML2OMML.XSL)
//
// Regenerate mml (after editing the corpus): npm run test:fixtures
// Daily regression needs no Office: it uses the frozen omml-ai/.
// Normalization matches the formula study: strip the <?xml?> declaration, unify m:oMath attributes.
// Known-diff cases (see KNOWN-DIFFS.md) keep their corpus entry and only warn, never block.
// ============================================================================

import { readFileSync, readdirSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { mathmlToOmml } from "../../packages/model/mathml2omml.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURES = join(__dirname, "..", "fixtures", "formula");
const MML_DIR = join(FIXTURES, "mml");
const REF_DIR = join(FIXTURES, "omml-ai");
if (!existsSync(MML_DIR)) {
  console.error("✗ 缺少 tests/fixtures/formula/mml/（KaTeX 中间产物，不入库）。先运行：npm run test:fixtures");
  process.exit(1);
}
const verbose = process.argv.includes("--verbose");

// Known diffs (see KNOWN-DIFFS.md): all fixed (204/204); the list is kept as an empty
// sentinel so any future diff must be registered explicitly or counts as a regression.
const KNOWN_DIFFS = new Map([]);

const no = (f) => Number(f.replace(/^mml-|\.xml$/g, ""));

/** Normalization aligned with the official output: strip XML declaration + unify m:oMath attrs. */
const norm = (s) => s.replace(/<\?xml[^>]*\?>\s*/g, "").replace(/<m:oMath[^>]*>/, "<m:oMath>").trim();

const files = readdirSync(MML_DIR).filter((f) => f.endsWith(".xml")).sort((a, b) => a.localeCompare(b, "en", { numeric: true }));
let pass = 0;
let known = 0;
const fails = [];
for (const f of files) {
  const n = no(f);
  const mml = readFileSync(join(MML_DIR, f), "utf-8");
  // omml-ai/ names mirror mml/ (minus the mml- prefix): mml-03.xml ↔ 03.xml
  const refName = f.replace(/^mml-/, "");
  const ref = readFileSync(join(REF_DIR, refName), "utf-8");
  let mine;
  try {
    mine = norm(mathmlToOmml(mml));
  } catch (e) {
    fails.push({ f, err: `转换器异常: ${e.message.slice(0, 100)}` });
    continue;
  }
  const refNorm = norm(ref);
  if (mine === refNorm) {
    pass += 1;
    if (verbose) console.log(`✓ ${f}`);
    continue;
  }
  // Known diff: warn without blocking (corpus stays for coverage; auto-passes once fixed)
  if (KNOWN_DIFFS.has(n)) {
    known += 1;
    console.warn(`⚠ ${f} [已知差异] ${KNOWN_DIFFS.get(n)}`);
    continue;
  }
  // Locate the first difference
  let i = 0;
  while (i < Math.min(mine.length, refNorm.length) && mine[i] === refNorm[i]) i++;
  fails.push({
    f,
    err: `diff @${i}\n    mine: …${mine.slice(Math.max(0, i - 60), i + 120)}…\n    ref : …${refNorm.slice(Math.max(0, i - 60), i + 120)}…`,
  });
}
console.log(`\n公式转换回归: ${pass}/${files.length} 与官方 XSLT 字节一致`);
if (known) console.log(`已知差异（见 KNOWN-DIFFS.md）: ${known} 个，警告不阻断`);
for (const fail of fails) {
  console.log(`✗ ${fail.f}`);
  if (verbose) console.log("   " + fail.err.replace(/\n/g, "\n   "));
}
process.exit(fails.length ? 1 : 0);
